_homepage:
    path:  /
    defaults: { _controller: WebKateTestTaskBundle:Default:index }

_executor_create:
    path: /ecexutor/create
    defaults: { _controller: WebKateTestTaskBundle:Default:createExecutor }

