_homepage:
    path:  /
    defaults: { _controller: WebKateTestTaskBundle:Default:index }

_executor_create:
    path: /executor/create
    defaults: { _controller: WebKateTestTaskBundle:Default:createExecutor }

_executors:
    path: /executors
    defaults: { _controller: WebKateTestTaskBundle:Default:executors }