<?php

namespace WebKate\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesWithProjects()
    {
        return $this->createQueryBuilder('c')
            ->select('c', 'p')
            ->leftJoin('c.projects', 'p')
            ->OrderBy('p.createdAt')
            ->getQuery()
            ->getResult()
        ;
    }
}