<?php

namespace WebKate\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExecutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExecutorRepository extends EntityRepository
{
    public function findAllOrderByCareerBeggining()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.careerBeggining')
            ->getQuery()
            ->getResult()
            ;
    }
}
