<?php

namespace WebKate\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findProjectsByCategoryId($categoryId)
    {
        return $this->createQueryBuilder('p')
            ->Where('p.category = :category_id')
            ->OrderBy('p.createdAt')
            ->setParameter('category_id', $categoryId)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getProjectsWithExecutors()
    {
        return $this->getEntityManager()
            ->createQuery(
            'SELECT p, e
            FROM WebKateTestTaskBundle:Project p
            LEFT JOIN projects_executors
            ON p.id = projects_executors.project_id
            LEFT JOIN WebKateTestTaskBundle:Executor e
            ON e.id = projects_executors.executor_id'
            )
        ;
    }
//    public function getProjectsWithExecutors()
//    {
//        return $this->createQueryBuilder('p')
//            ->select('p', 'e')
//            ->leftJoin('p.executors', 'e')
//            ->OrderBy('e.createdAt')
//            ->getQuery()
//            ->getResult()
//        ;
//    }
}