<?php

namespace WebKate\Bundle\TestTaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function findProjectsByCategoryId($categoryId)
    {
        return $this->createQueryBuilder('p')
            ->Where('p.category = :category_id')
            ->OrderBy('p.createdAt')
            ->setParameter('category_id', $categoryId)
            ->getQuery()
            ->getResult()
        ;
    }
} 